search_books:
  path: /search
  controller: App\Controller\HomeController::searchBooks
  methods: [POST]

controllers:
    resource: ../../src/Controller/
    type: annotation
    
kernel:
    resource: ../../src/Kernel.php
    type: annotation
